config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :photos, except: [:update, :destroy, :edit] do
    get 'all', on: :collection
    resources :comments, only: [:create]
  end

  resources :followings, only: [:create, :destroy], param: :slug

  resources :users, only: :index

  get '/:slug', to: 'users#profile', as: 'user_profile'

  root 'photos#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
end

app/models/following.rb
class Following < ActiveRecord::Base
  belongs_to :user
  belongs_to :user_following, class_name: 'User'
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  has_attached_file :asset,
                    styles: {
                        thumb: "70x70",
                        medium: "500x500"
                    },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :asset,
                                    content_type: /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    styles: {
                        medium: "300x300>",
                        thumb: "40x40#"
                    },
                    default_url: Proc.new{ |a| a.instance.get_gravatar }

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :user_name, presence: true, uniqueness: { case_sensitive: false }

  has_many :photos
  has_many :comments
  has_many :followings
  has_many :followers, class_name: 'Following', foreign_key: 'user_following_id'

  has_many :followed_users, through: :followings, source: :user_following
  has_many :follower_users, through: :followers,  source: :user

  friendly_id :user_name, use: :slugged

  def get_gravatar
    "//gravatar.com/avatar/"+Digest::MD5.hexdigest(email)
  end

  def follow_user?(user)
    if followings.where(user_following_id: user.id).first
      true
    else
      false
    end
  end

  def followings_count
    followings.count
  end

  # This method is used in photos#index to show photos of the followed users and mine
  def followed_users_and_me
    followings.map{|u| u.user_following_id} + [id]
  end

  def followed_users_ids
    followings.map{|u| u.user_following_id}
  end

  private

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :avatar) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :current_password, :avatar) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    photo = Photo.find(params[:photo_id])
    user_id = current_user.id

    @comment = photo.comments.build(comment_params)
    @comment.user_id = user_id

    if @comment.save
      redirect_to photo_path(photo), notice: 'Your comment has been added'
    else
      redirect_to new_photo_comment_path(photo)
    end

  end

  def comment_params
    params.require(:comment).permit(:body, :photo_id)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :authenticate_user!
  expose(:user) { User.friendly.find(params[:slug]) }

  def create
    if can_follow?
      following = current_user.followings.build( user_following_id: user.id)
      @success = following.save
    end
  end

  def destroy
    following = current_user.followings.where(user_following_id: user.id).first
    @success = following.destroy
  end

  private

  def can_follow?
    if current_user.id == user.id || current_user.followed_users_ids.include?(user.id)
      false
    else
      true
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    if user_signed_in?
      @photos = Photo.where(user_id: current_user.followed_users_and_me)
    else
      @photos = Photo.includes(:user).all
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.build(photo_params)

    if @photo.save
      redirect_to photo_path(@photo), notice: 'The photo has been uploaded'
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @comments = @photo.comments.all.includes(:user)
  end

  def all
    @photos = Photo.includes(:user).all
  end

  private

  def photo_params
    params.require(:photo).permit(:title, :description, :asset)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user)   { User.friendly.find(params[:slug])}
  expose(:photos) { user.photos }
  expose(:users)

  def index; end
  def profile; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_avatar(user)
    image_tag user+"?d=identicon&amp;f=y"
  end

  def my_profile?
    current_user.slug == params[:slug]
  end

end

app/views/followings/create.js.erb
$("#following").html("<%= escape_javascript(render('users/following', user: user)) %>");

app/views/followings/destroy.js.erb
$("#following").html("<%= escape_javascript(render('users/following', user: user)) %>");

app/views/layouts/application.html.slim
doctype html
html
head
  title Rails Instagram
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags
body
  .container-page
    .notice
      = notice
    .alert
      = alert

    = render partial: 'shared/header'

    .content
      = yield

app/views/photos/_form.slim
= form_for(@photo) do |f|
  .fields
    .field
      = f.label :title
      = f.text_field :title
    br
    .field
      = f.label :description
      = f.text_area :description
    br
    .field
      = f.label :asset
      = f.file_field :asset
    br
  .actions
    .action
      = f.submit

app/views/photos/_new_comment_form.slim
= form_for([@photo, @comment]) do |f|

  .fields
    .field
      = f.text_area :body

  .actions
    .action
      = f.submit

app/views/photos/_photo.slim
.item
  div = photo.title
  div = photo.description
  div = link_to photo_path(photo) do
    = image_tag photo.asset.url(:medium)
  div
    = link_to user_profile_path(photo.user.slug) do
      = photo.user.user_name

app/views/photos/all.html.slim
.inner-container
  h1 Listing photos
  br

  - if @photos.any?
    .items
      = render @photos

  - else
    |No photo

app/views/photos/index.html.slim
.inner-container
  h1 Listing photos
  br

  - if @photos.any?
    .items
      = render @photos

  - else
    |No photo

app/views/photos/new.html.slim
.inner-container
  h1 New photo
  br
  = render partial: 'form'

app/views/photos/show.html.slim
.inner-container
  h1 Show photo
  br
  .item.show
    div = @photo.title
    div = @photo.description
    = image_tag @photo.asset.url(:medium)

  .comments
    h2 Comments
    br
    - @comments.each do |comment|
      .comment
        div
          = link_to user_profile_path(comment.user.user_name) do
            = get_avatar(comment.user.avatar.url(:thumb))
        div = link_to comment.user.user_name, user_profile_path(comment.user.user_name)
        div = comment.body
    br

    - if user_signed_in?
      h3 Give your comment
      = render partial: 'new_comment_form'
    - else
      |You must logged to comment.&nbsp;
      = link_to 'Login', new_user_session_path
      |&nbsp;
      = link_to 'Register', new_user_registration_path

app/views/shared/_header.slim
header
  .inner-container
    .left
      = link_to 'RailsInstagram', root_path, class: 'logo'
      = link_to 'Users list', users_path, class: 'item-menu'
      - if user_signed_in?
        = link_to 'New photo', new_photo_path, class: 'item-menu'
        = link_to 'My profile', user_profile_path(current_user.slug), class: 'item-menu'
        = link_to 'All photos', all_photos_path, class: 'item-menu'

    .right
      - if user_signed_in?
        .navigation#js-navigation
          .avatar
            = get_avatar(current_user.avatar.url(:thumb))
            i.icon-arrow-down
          ul
            li
              = link_to current_user.user_name, user_profile_path(current_user.slug)
            li
              = link_to 'Edit account', edit_user_registration_path
            li
              = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        .login
          = link_to 'Sign In', new_user_session_path
          |&nbsp;Or&nbsp;
          = link_to 'Sign Up', new_user_registration_path

app/views/users/_following.slim
- if current_user.follow_user?(user)
  = button_to 'Unfollow!', following_path(user.slug), method: :delete, remote: true
- else
  = button_to 'Follow', followings_path(slug: user.slug), remote: true

app/views/users/index.html.slim
.inner-container
  h1 Users list
  br

  - users.each do |user|
    div
      = link_to user.user_name, user_profile_path(user.slug)

app/views/users/profile.html.slim
.inner-container
  .profile
    .left
      div
        = get_avatar(user.avatar.url(:medium))
      h2
        = user.user_name
      div
        = user.email

      - if user_signed_in? && !my_profile?
        #following
          = render 'following', user: user

      br
      h4 Followed users:
      - if user.followings_count > 0
        = user.followings_count
      - else
        |No followed users

      h4 Followers:
      |Not implemented yet

    .right
      - if photos.any?
        - photos.each do |photo|
          .item
            div = photo.title
            div = photo.description
            div
              = image_tag photo.asset.url(:medium)

      - else
        |No photos

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>